name: scan-and-run

on:
  workflow_dispatch:
    inputs:
      agent:
        description: "Agent to run (e.g., GrantFinder-001, BookWriter-001)"
        required: true
        type: string
      dry_run:
        description: "If true, skip agent execution after scan"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  scan_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout StegAgents
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          python -m pip install -q pytest || true

      - name: Scan repo for forbidden external dependency usage (hard fail)
        run: |
          set -euo pipefail
          python scripts/scan_no_stegid.py

      - name: Mint local receipt (inline)
        id: receipt
        shell: bash
        env:
          SV_AGENT: ${{ inputs.agent }}
        run: |
          set -euo pipefail

          RECEIPT_JSON="$(python - <<'PY'
import json, os, datetime
agent = os.getenv("SV_AGENT", "unknown")
now = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
receipt = {
  "issuer": "local",
  "agent": agent,
  "issued_at": now,
  "verified": True,
  "verifier": "local-receipt",
  "note": "CI-local receipt; no external receipt authority required."
}
print(json.dumps(receipt, separators=(",", ":")))
PY
)"
          printf '%s\n' "receipt_json=$RECEIPT_JSON" >> "$GITHUB_OUTPUT"
          printf '%s\n' "SV_RECEIPT_JSON=$RECEIPT_JSON" >> "$GITHUB_ENV"

      - name: Run agent (unless dry-run)
        if: ${{ inputs.dry_run == false }}
        env:
          SV_RECEIPT_JSON: ${{ steps.receipt.outputs.receipt_json }}
        run: |
          set -euo pipefail
          echo "▶️ Running agent: ${{ inputs.agent }}"
          python -m src.agent_runner --agent "${{ inputs.agent }}"

      - name: Commit if changed
        if: ${{ inputs.dry_run == false }}
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "stegverse-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "agent: run ${{ inputs.agent }} (scan-and-run)"
          git push
